when:
  - event: push
    branch: master

steps:
  - name: gen 
    image: ruby:3.2 
    commands: |
      sha=$(git rev-parse --short HEAD)
      git config --global user.name "Rajdeep Malakar"
      git config --global user.email "rajdeepm.dev@gmail.com"
      
      gem install ronn-ng >/dev/null

      ronn --roff man/hay_flags.md --manual=hay/flags.h --organization="Hay Foundation"
      git add man/hay_flags.3
      git commit -s -m "[$sha] manpage [CI SKIP]"
      git remote remove origin
      mkdir -p $HOME/.ssh
      echo "${ssh_pub}" > /$HOME/.ssh/id_rsa.pub

  - name: push
    image: appleboy/drone-git-push
      settings:
        remote_name: origin
        branch: master
        local_ref: master
        ssh_key:
          from_secret: ssh_key
        remote: git@codeberg.org:hay/flags.git