steps:
  build:
    image: alpine
    when:
      branch: [master]
      event: [push, pull_request]
    commands: |
      # alpine uses build-base for dev utilies such as system headers, make etc.
      apk add --no-cache cmake build-base gcc >/dev/null
      # treat warnings as errors. assuming the Makefile respects enviornment $CFLAGS
      export CFLAGS="-Wall"
      # mkdir
      mkdir -pv build
      cd build
      # configure and build
      cmake ..
      cmake --build .
      # test
      ctest
